dataset: "multi_kr"

path:
  corpus_path: "/home/dhseong/work/data/kr/multi_kr_16k"
  raw_path: "./raw_data/multi_kr"
  preprocessed_path: "./preprocessed_data/multi_kr"
  mfa_path: "./raw_data/multi_kr_mfa"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["korean_cleaners"]
    language: "kr"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
