seed: 1234
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 1
path:
  ckpt_path: "./output/ckpt/VCTK"
  log_path: "./output/log/VCTK"
  result_path: "./output/result/VCTK"
optimizer:
  batch_size: 32
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 200000
  log_step: 100
  synth_step: 2000
  val_step: 2000
  save_step: 50000
